<?php
drupal_add_js(drupal_get_path('module', 'uni_cas') .'/unicas.js');
?>

<?php
function uni_cas_form_user_register_alter(&$form, &$form_state) {
  // Modification for the form with the given form ID goes here. For example, if
  // FORM_ID is "user_register" this code would run only on the user
  // registration form.

  // Run the Ajax and Onkeyup functions here
   $form['Add user'] = array(
  '#type' => 'textfield',
  '#title' => t('Ajax-based add user'),
  '#default_value' => $object['Add user'],
  '#size' => 60,
  '#maxlength' => 64,
  '#description' => t('Should run Ajax'),
  '#id' => 'edit-name',
);


}
?>

<p>Suggestions: <span id="txtHint"></span></p>

