<html>
<head>
<script type="text/javascript">
function showHint(str)
{
if (str.length==0)
  {
  document.getElementById("txtHint").innerHTML="";
  return;
  }
if (window.XMLHttpRequest)
  {// code for IE7+, Firefox, Chrome, Opera, Safari
  xmlhttp=new XMLHttpRequest();
  }
else
  {// code for IE6, IE5
  xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
xmlhttp.onreadystatechange=function()
  {
  if (xmlhttp.readyState==4 && xmlhttp.status==200)
    {
    document.getElementById("txtHint").innerHTML=xmlhttp.responseText;
    }
  }
xmlhttp.open("GET","sites/all/modules/uni_cas/unicasfiles/userhint.php?q="+str,true);
xmlhttp.send();

}


</script>
</head>
<body>

<p><b>Start typing a name in the input field below:</b></p>
<form>
User name: <input type="text" id="entered" onkeyup="showHint(this.value)" size="20" /> <input type="checkbox" name="option1" value="" />
</form>
<p>Suggestions: <span id="txtHint"></span></p>

</body>
</html>
