<?php
drupal_add_js(drupal_get_path('module', 'uni_cas') .'/unicas.js');
?>

<?php
  /**
   * Implementation of hook_form_alter().
   *
   * The function is named modulename_form_alter.
   */
  function uni_cas_form_alter(&$form, $form_state, $form_id) {
    // Normally a switch is used because you may want to alter more than
    // one form and it is easy to add a new case for each form.
    switch ($form_id) {
      // This is our form ID.
      case 'user_register':
      
       $form['name']['#title'] = t('Ajax Based ID');                     // Our kickin' mods go here.      
       $form['name']['#description'] = t('Suggestions:');       
        
        break;
    }
  }
?>

<p>Suggestions: <span id="txtHint"></span></p>
