<?php
drupal_add_js(drupal_get_path('module', 'uni_cas') .'/unicas.js');
?>


<?php

function uni_cas_menu() {

  $items['admin/user/user/create'] = array(
    'title' => 'Add user', 
    'page arguments' => array('create'), 
    'access arguments' => array('administer users'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'user.admin.inc',
    'id' => 'entered',
    'onkeyup' => 'showHint(this.value)', 
  );
 
 return $items; 
}


?>

<p>Suggestions: <span id="txtHint"></span></p>

